--- 
title: "Modelo Estratégico de Focalización del Dengue en áreas urbanas de México"
author: "Felipe Antonio Dzul Manzanilla"
date: "2021: Last compiled `r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
biblio-style: apalike
link-citations: yes
github-repo: fdzul/strategic_mod_den_targeting
description: "El libro describe el Modelo Estratégico de Focalización del Dengue en áreas urbanas de México"
---

# Prologo {-}

El planteamiento de un modelo estratégico para la focalización del control integrado de las arbovirosis transmitidas por *Aedes aegypti* asociado a los manuales (**identificación de los hotspots de dengue en zonas urbanas**) para su implementación en los servicios de la Salud en los estados constituye una guía operativa para el análisis espacial de los hotspots de los casos de dengue y los hotspots del vector.

El documento, los manuales y los paquetes en R asociados con el modelo estratégico para la focalizacion fueron inspirados por la necesidad de contribuir en la toma de desiciones del programa de prevención y control de las arbovirosis transmitidas por *Aedes aegypti*, específicamente en la identificación de los hotspots de la transmisión y la focalizacion de las acciones antivectoriales. Así mismo es inspirado por [**bookdown**](https://github.com/rstudio/bookdown) y todas las iniciativas the Free and Open Source Software. El libro es de código abierto y asegura que el contenido es reproducible en los servicios de salud de México.

La iniciativa de escribir e instrumentar la identificación de los hostpos del dengue y su vector como un modelo de estratificación fue soportada por la [Secretaría de Salud del Estado de Veracruz](https://www.ssaver.gob.mx/) & el
[CENAPRECE](https://www.gob.mx/salud/cenaprece)**

## Justificación {-}
El programa de prevención y control del dengue en México se enfrenta a grandes desafíos que incluyen:

 - 1) Expanción geográfica del dengue.
 - 2) Incremento de la transmisión en zonas endémicas y no endémicas.
 - 3) Presencia de brotes en zonas urbanas que contituyen grandes metropolis (Guadalajara, Monterrey, La comarca Lagunera, etc).
 - 4) Potencial introducción de nuevos agentes causales, como la Fiebre Amarilla y Mayaro.
 - 5) El modelo de estratificación actual es límitado y no tiene resolución espacial  para identificar el riesgo en las áreas urbanas (ciudades o metropolis).


El desarrollo de un modelo estratégico de focalización de las acciones antivectoriales en las áreas urbanas endémicas de México y su implementación, constituye un elemento clave para redirigir los límitados recursos materiales, humanos y económicos a las áreas de los grandes centros urbanos donde la transmisión se concentra (basados en datos históricos) y donde las cadenas de transmisión son activas (datos actuales). Teóricamente, de acuerdo a la ley de Pareto 80/20, si el 80% de la transmisión se concentra en el 20% del área urbana, la focalización de las acciones en el 20% del área, permitiría obtener reducciones del 80% de la transmisión. 

Indirectamente el modelo estratégico de focalización tiene como objeto determinar esta ley de Pareto para la transmisión de dengue en las áreas urbanas endémicas.

## Estructura del Libro {-}



## Software & Convenciones {-}

## Agradecimientos {-}


# Autores {-}

## Felipe Antonio Dzul Manzanilla {-}

## Fabián Correa Morales {-}
